### ISSUE TITLE
Q5 Help wanted

### ISSUE THREAD

**Issue by Zanark** [Zanark/Project-Euler-Solutions#1]
This is the only solution that I could come up with at the moment     &nbsp;&nbsp;&nbsp;  😓 
It takes around 3 minutes to run and display the output. 

I would be happy if someone helped me to make it better and also explain me how it works
because it's no use if I myself can't understand it.

[Link to Q5.py](https://github.com/Zanark/Project-Euler-Solutions/blob/d886d4b8bc37cc31629b63fb8248736559bc7b11/Python/Q5/q5.py#L1)

**Comment by Zanark** [comment]
@SubhrajitPrusty 
Can u plz help me on this

**Comment by SubhrajitPrusty** [comment]
It's basically asking for the LCM of the numbers.
